# Site settings
title: Seven Seconds was an Eternity!
email: perfforensics@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  My name is Steve Feldman. You may or may not know me. Somehow you stumbled across my blog because most likely I didn’t tell you it exists. I am married to a beautiful woman named Jenny. I have two adventurous and fearless daughters named Caroline and Molly. After 11 crazy and fun years @Blackboard, I've been fortunate to head up Engineering at Contrast Security.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://stevefeldman.github.io" # the base hostname & protocol for your site
twitter_username: PerfForensics
github_username:  SteveFeldman

# Build settings
markdown: kramdown
