# Site settings
title: Seven Seconds was an Eternity!
email: perfforensics@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Somehow you stumbled across my blog. I hope you enjoy it. I will try my hardest to add entries that are meaningful and worthwhile.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://stevefeldman.github.io" # the base hostname & protocol for your site
twitter_username: PerfForensics
github_username:  SteveFeldman

# Build settings
markdown: kramdown
